### ISSUE TITLE
Issue with hanging connection

### ISSUE THREAD

**Issue by markosski** [svroonland/zio-amqp#90] opened 2020-12-01 00:23 UTC
I have an application that needs two long lived RabbitMQ connections. Application is deployed to ECS cluster and running in docker container. When troubleshooting application running in ECS I narrowed down the issue with application hanging on second connection. Looks like hanging happens around this code `effectBlocking(factory.newConnection(eces))`
When trying to replicate issue on local machine I was able to see the same happening with following container arg `--cpus=1.0`

Any value for --cpus greater than 1.0, e.g. 1.01 does not causes this issue.

I'm using slightly modified version of this library, here's the code for connection.

```
  def connect[E <: Blocking with Clock](factory: ConnectionFactory, connectionRetry: Schedule[E, Any, Long]): ZManaged[E, Throwable, Connection] =
    ZIO.runtime[E]
      .flatMap { runtime => 
        val eces = runtime.platform.executor.asECES
        factory.useNio()
        factory.setNioParams(new NioParams().setNioExecutor(eces))
        ZIO.effect(logger.debug("Creating connection")) *>
        effectBlocking(factory.newConnection(eces))
      }
      .tap(c => ZIO.effect(logger.info(s"Connection established: $c")))
      .tapError(err => ZIO.effect(logger.warn(s"Can't connect to ${factory.getHost()}; Error: $err")))
      .toManaged(c => UIO { 
        c.close()
      })
      .retry(connectionRetry)
```

**Comment by markosski** [comment] 2020-12-01 00:34
Disabling Nio seems to be fixing the issue 🤔

**Comment by svroonland** [comment] 2020-12-01 12:05
Thanks for reporting @markosski. I'll see if I can reproduce and find the cause.

**Comment by svroonland** [comment] 2021-01-11 18:35
Hi @markosski , apologies for the late feedback, I did spend a couple of hours trying to reproduce it, but I'm unable to spend more time on it in the near future. If you have some code that reproduces the issue, that would be greatly appreciated.

**Comment by markosski** [comment] 2021-01-27 03:08
Hey thanks @svroonland . I will try to come up with minimal example to reproduce.

**Comment by simpadjo** [comment] 2021-03-01 18:47
@markosski I assume it cold happen because you pass the same `eces` to `factory.setNioParams(new NioParams().setNioExecutor(eces))` and  `factory.newConnection(eces)`. Note that in `factory.newConnection` this parameter is optional.
In a single-threaded environment this might lead to a deadlock if rabbitMq blocks while establishing the connection.

**Comment by markosski** [comment] 2021-03-03 13:30
@simpadjo that's a valid point. Original code here uses the same eces as well -> https://github.com/svroonland/zio-amqp/blob/master/src/main/scala/nl/vroste/zio/amqp/Client.scala#L173

Perhaps ZIOs blocking executor should be passed instead, let me test it out.

**Comment by markosski** [comment] 2021-03-06 14:56
@svroonland @simpadjo 
Here's a repo that replicates the issue. In order to replicate it when running application, we want to limit number of CPUs available to JVM to 1 cpu.

https://github.com/markosski/zio-amqp-test/blob/master/amqp/src/main/scala/HelloWorld.scala

In this repo I included a copy of zio-amqp code with modified executor in the connection to use blocking executor instead the one provided in runtime.
https://github.com/markosski/zio-amqp-test/blob/master/amqp/src/main/scala/amqp.scala#L170

You can replicate it with following steps. 
1. Uncomment `import nl.vroste.zio.amqp._`, comment back `import amqp._`
2. Go to sbt and run assembly
3. Run application - `java -XX:ActiveProcessorCount=1 -jar target/scala-2.13/amqp-assembly-0.0.1-SNAPSHOT.jar`
4. You will notice 2 connections will be created but application will hang on channels and become unresponsive. Need to kill process to exit.

Using modified connection:
1. Make sure modified zio-amqp is imported `import amqp._`
2. Assembly and run application, application will start as expected.

**Comment by svroonland** [comment] 2021-03-08 21:17
Hi @markosski, I would expect that using the blocking executor would make a difference, since it has a max thread pool size of 1000 (see https://github.com/zio/zio/blob/master/core/jvm/src/main/scala/zio/blocking/package.scala#L218), while the standard ZIO executor has a thread pool size of 2 * core count (see https://github.com/zio/zio/blob/master/core/jvm/src/main/scala/zio/internal/DefaultExecutors.scala#L9).  I haven't tested it yet, but do I understand correctly that your modified version with the blocking executor works as desired?

**Comment by svroonland** [comment] 2021-03-08 21:29
And to be completely honest, the whole NIO setup sharing the ZIO threadpool should be investigated more thoroughly. I'm not sure if it is best to have the rabbitmq client share the ZIO executor & threadpool or to have a dedicated one.

**Comment by quelgar** [comment] 2021-03-08 21:55
If you're using NIO channels in blocking mode, you definitely want to do all the NIO stuff using `zio.blocking` or something configured similarly. You could use a dedicated pool, but I'm not sure it's necessary.

Also watch out for host name resolution, usually via `InetAddress`, which can block for a while. It's probably worth doing this on the blocking pool as well.

Once you've got that sorted, you need to worry about interrupting blocking I/O calls when the fiber is interrupted. This is done by closing the channel on interrupt.

**Comment by markosski** [comment] 2021-03-08 22:51
@svroonland yes, it worked as expected in a sense it did not hang the application on channel creation since both threads were already blocked by 2 connections. The change I made is only an example not the complete solution so I agree with you more research is needed here. 
@quelgar could you expand more on `worry about interrupting blocking I/O calls when the fiber is interrupted` ?

**Comment by svroonland** [comment] 2021-03-10 07:50
For now I would say that it's probably best to use the blocking executor in both places we pass the ZIO executor. Possibly the NIO threads could share the ZIO pool, but we'd have to look into rabbitmq more.

Would you be willing to make a PR with the change you made @markosski ?

**Comment by quelgar** [comment] 2021-03-11 19:58
> @quelgar could you expand more on worry about interrupting blocking I/O calls when the fiber is interrupted ?

It's only tangentially related to this issue. But if your channel reads/writes are blocking, the ZIO fiber will not be interruptible while a blocking read/write is in progress, unless you take an extra step of adding interrupt handling. This is likely to cause problems at some point, as ZIO programs often rely on interruption working for correct operation.

[This is how I do it on my zio-nio branch](https://github.com/zio/zio-nio/blob/e237fd684c4a2205a7d1a5df4fc551f179654202/nio/src/main/scala/zio/nio/channels/Channel.scala#L37). So it just forks and sets up on `onInterrupt` to close down the channel (which is the only way to interrupt a NIO blocking I/O call).

**Comment by svroonland** [comment] 2021-03-27 10:42
Maybe it's safest to let the rabbitmq library manage its own thread pool and just use ZIO for the interop, to avoid any risks like in this issue. I made a PR with that change (#90), let me know if that would work for you @markosski

**Comment by markosski** [comment] 2021-04-04 01:52
@svroonland I'm ok with the approach.

**Closed** 2021-04-04 09:07 UTC
Labels: help wanted

**Comment by devsprint** [comment] 2021-04-22 14:38
@svroonland I had a similar problem with a service running zio-amqp version 0.1.5 running in docker. The issue was reproduced only when I was running the docker container inside a pod in k8s but did not reproduced when I was running it locally, but still in docker.   Looking for a new release of the library.
